# Generated by Django 3.1.6 on 2021-02-10 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='status_tarefa',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status_tarefa',
            field=models.ManyToManyField(related_name='tarefa_adicionada', to=settings.AUTH_USER_MODEL),
        ),
    ]
