# Generated by Django 3.1.6 on 2021-02-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_auto_20210209_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='status_tarefa',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status_tarefa',
            field=models.CharField(default='PENDENTE', max_length=9),
        ),
    ]
